name: nosso
description: sistema de e-commerce

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

androidX: true

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  http: ^0.13.1
  dio: ^4.0.0
  mobx: ^1.2.1+4
  flutter_mobx:
  build_runner:
  mobx_codegen:
  get_it:
#  shared_preferences: ^0.5.8
  http_parser: ^4.0.0
  get: ^3.26.0

  steps: ^1.0.1
  carousel_pro: ^1.0.0
  fluttertoast: ^3.1.0
  image_picker: ^0.7.4
  image_picker_web: any
  file: ^6.1.0
  image_cropper: ^1.3.1
  flutter_colorpicker: ^0.3.5
  dropdown_search: ^0.4.9
  search_choices: ^2.0.3
  multiselect_dropdown: ^2.0.0+1
  skeleton_loader: ^1.0.2+3

  geolocator: ^7.0.1
  geocoding: ^2.0.0
  flutter_polyline_points: ^0.2.4

  stream_transform: ^2.0.0
  google_maps_flutter: ^2.0.1
  geocoder: ^0.2.1
  location: ^4.1.1

  barcode_flutter: ^1.1.2
  barcode_scan: ^1.0.0
  webview_flutter: ^1.0.7
  url_launcher: ^6.0.3
#  audioplayers: ^0.18.2
  path_provider: ^2.0.1
  flutter_multi_carousel: ^1.0.3
  flutter_paginator: ^0.0.6
  cached_network_image: ^3.0.0

  masked_text_input_formatter: ^0.0.1
  datetime_picker_formfield:
  flutter_masked_text: ^0.8.0
  mask_text_input_formatter: ^1.1.0
  intl:
#  brasil_fields: ^0.4.0

  cupertino_icons: ^1.0.0
  flutter_feather_icons:
  google_fonts:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audios/
